#!/usr/bin/env bash
# Regenerate THIRD-PARTY-NOTICES.txt from the ACTUAL dependency graph.
#
# Cackle redistributes third-party code two ways: Go modules compiled into
# the single static binary (chi, modernc.org/sqlite, golang.org/x/crypto,
# oklog/ulid, ...) and the npm graph bundled into the embedded React UI
# (React, Vite, Tailwind, shadcn/radix primitives, ...). MIT, BSD, ISC and
# Apache-2.0 all require the copyright notice and licence text to accompany
# every copy — this script reproduces those from the real module/package
# graphs rather than hand-maintaining a list that drifts.
#
#     ./scripts/gen-notices.sh
#
# THIRD-PARTY-NOTICES.txt is committed at the repo root. It is NOT
# hand-maintained — re-run this after changing go.mod or web/package.json.
#
# Degrades gracefully: if web/ has no package.json yet (frontend not
# scaffolded), or a tool can't be installed (no network), that section is
# skipped with an explanatory note rather than failing the whole run — this
# script must never be the reason `make check` is red for reasons unrelated
# to licensing.
set -uo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

OUT="THIRD-PARTY-NOTICES.txt"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

echo "==> generating $OUT"

# ── Go modules ────────────────────────────────────────────────────────────────
GO_NOTICES="$TMP/go-notices.txt"
GO_STATUS="skipped (no go.mod)"
if [[ -f go.mod ]]; then
  DETECTOR="$(command -v go-licence-detector || true)"
  if [[ -z "$DETECTOR" ]]; then
    echo "==> installing go.elastic.co/go-licence-detector@v0.10.0"
    if GOBIN="$TMP/bin" go install go.elastic.co/go-licence-detector@v0.10.0 2>"$TMP/go-install.err"; then
      DETECTOR="$TMP/bin/go-licence-detector"
    else
      echo "    could not install go-licence-detector (no network?) — skipping Go section"
      cat "$TMP/go-install.err" >&2 || true
    fi
  fi

  if [[ -n "$DETECTOR" ]]; then
    echo "==> resolving Go module graph"
    if go mod download 2>"$TMP/go-mod.err" \
      && go list -m -json all 2>>"$TMP/go-mod.err" | "$DETECTOR" \
           -includeIndirect \
           -rules scripts/notices/go-licence-rules.json \
           -noticeTemplate scripts/notices/go-modules.tmpl \
           -noticeOut "$GO_NOTICES" 2>>"$TMP/go-mod.err"
    then
      GO_STATUS="ok"
    else
      echo "    go module notice generation failed:" >&2
      cat "$TMP/go-mod.err" >&2 || true
      GO_STATUS="failed (see stderr above) — section omitted"
      : > "$GO_NOTICES"
    fi
  else
    : > "$GO_NOTICES"
  fi
else
  : > "$GO_NOTICES"
fi

# ── npm packages (web/) ───────────────────────────────────────────────────────
NPM_NOTICES="$TMP/npm-notices.txt"
NPM_STATUS="skipped (web/package.json not present yet)"
if [[ -f web/package.json ]]; then
  echo "==> resolving npm dependency graph (web/)"
  if [[ ! -d web/node_modules ]]; then
    ( cd web && npm ci --no-audit --no-fund 2>"$TMP/npm-install.err" ) || \
      ( cd web && npm install --no-audit --no-fund 2>>"$TMP/npm-install.err" )
  fi
  if npx --yes license-checker-rseidelsohn \
      --production --json --excludePrivatePackages --start web \
      2>"$TMP/npm-lc.err" | node scripts/notices/npm-notices.mjs > "$NPM_NOTICES" 2>>"$TMP/npm-lc.err"
  then
    NPM_STATUS="ok"
  else
    echo "    npm notice generation failed:" >&2
    cat "$TMP/npm-lc.err" >&2 || true
    NPM_STATUS="failed (see stderr above) — section omitted"
    : > "$NPM_NOTICES"
  fi
else
  : > "$NPM_NOTICES"
fi

# ── Compose ───────────────────────────────────────────────────────────────────
{
  cat <<HEADER
================================================================================
Cackle — THIRD-PARTY NOTICES
================================================================================

This file is generated by scripts/gen-notices.sh from the actual dependency
graph. Do not edit it by hand.

Cackle is distributed under the MIT licence (see LICENSE). It bundles the
third-party software listed below. Each entry gives the component name, its
version, the licence it is distributed under, and the full text of that
licence, as those licences require.

Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
Go modules section : ${GO_STATUS}
npm packages section: ${NPM_STATUS}

HEADER

  if [[ -s "$NPM_NOTICES" ]]; then
    echo "================================================================================"
    echo "npm packages (bundled into the Cackle web UI)"
    echo "================================================================================"
    echo
    cat "$NPM_NOTICES"
  fi

  echo "================================================================================"
  echo "Go standard library (compiled into the cackle binary)"
  echo "================================================================================"
  echo
  echo "--------------------------------------------------------------------------------"
  echo "Component : The Go Programming Language standard library"
  echo "Version   : $(go env GOVERSION 2>/dev/null || echo unknown)"
  echo "Licence   : BSD-3-Clause (plus the Go patent grant, reproduced below)"
  echo "--------------------------------------------------------------------------------"
  echo
  if GOROOT_DIR="$(go env GOROOT 2>/dev/null)" && [[ -f "$GOROOT_DIR/LICENSE" ]]; then
    cat "$GOROOT_DIR/LICENSE"
    echo
    [[ -f "$GOROOT_DIR/PATENTS" ]] && cat "$GOROOT_DIR/PATENTS"
    echo
  fi

  if [[ -s "$GO_NOTICES" ]]; then
    echo "================================================================================"
    echo "Go modules (compiled into the cackle binary)"
    echo "================================================================================"
    echo
    cat "$GO_NOTICES"
  fi
} > "$OUT"

echo "==> wrote $OUT ($(wc -l < "$OUT" | tr -d ' ') lines)"
